steps:
  - id: npm-ci
    name: node:22-bookworm
    entrypoint: bash
    args:
      - -ceu
      - |
        npm install -g "npm@${_NPM_VERSION}"
        npm --version
        npm ci

  - id: lint
    name: node:22-bookworm
    entrypoint: bash
    args:
      - -ceu
      - |
        npm install -g "npm@${_NPM_VERSION}"
        npm run lint

  - id: test
    name: node:22-bookworm
    entrypoint: bash
    args:
      - -ceu
      - |
        npm install -g "npm@${_NPM_VERSION}"
        npm run test

  - id: build
    name: node:22-bookworm
    entrypoint: bash
    args:
      - -ceu
      - |
        npm install -g "npm@${_NPM_VERSION}"
        npm run build

substitutions:
  _NPM_VERSION: "10.9.0"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
