version: '3.8'

services:
  app:
    build: .  # เพิ่มบรรทัดนี้เพื่อบอกให้ build จาก Dockerfile ในโฟลเดอร์ปัจจุบัน
    image: gogocash_api
    container_name: gogocash-api
    ports:
      - '3000:3000'
    # ใช้ env_file เพื่อโหลดตัวแปรจากไฟล์ .env
    env_file:
      - .env
    # หากต้องการใช้ไฟล์ .env.production ให้ระบุ
    # env_file:
    #   - .env.production