import type { ProcessingActivity } from "../types";

export const DEFAULT_PROCESSING_ACTIVITIES: ProcessingActivity[] = [
  {
    activityId: "PA-001",
    activityName: "User Registration & Identity Verification",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand (see privacy policy)",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Account creation and verification",
    legalBasis: "CASHBACK_TRACKING / CONTRACT",
    dataCategories: ["identity", "contact"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "3 years after account closure (profile)",
    retentionJustification: "Contract + PDPA",
    crossBorderTransfers: true,
    transferSafeguards: "SCCs with subprocessors",
    securityMeasures: ["encryption in transit", "access control"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-002",
    activityName: "Cashback Transaction Tracking",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Track eligible purchases for cashback",
    legalBasis: "CASHBACK_TRACKING",
    dataCategories: ["transaction", "merchant identifiers"],
    dataSubjectCategories: ["registered users"],
    recipients: [{ name: "Merchant partners", role: "PROCESSOR", country: "Various" }],
    retentionPeriod: "5 years",
    retentionJustification: "Regulatory / BOT-aligned retention",
    crossBorderTransfers: true,
    transferSafeguards: "DPA + SCC",
    securityMeasures: ["TLS", "RBAC"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-003",
    activityName: "Wallet Balance Management",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Display and settle wallet / withdrawal",
    legalBasis: "CONTRACT",
    dataCategories: ["financial", "wallet"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "5 years for transaction artifacts",
    retentionJustification: "Legal / tax",
    crossBorderTransfers: false,
    transferSafeguards: null,
    securityMeasures: ["encryption"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-004",
    activityName: "AI Credit Score Assessment",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Credit eligibility profiling",
    legalBasis: "AI_CREDIT_SCORING / EXPLICIT_CONSENT",
    dataCategories: ["behavioral", "financial"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "2 years inputs",
    retentionJustification: "DPIA + policy",
    crossBorderTransfers: true,
    transferSafeguards: "SCC",
    securityMeasures: ["RBAC", "audit"],
    dpiaRequired: true,
    dpiaReference: "legal/dpia/dpia-ai-credit-scoring.md",
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-005",
    activityName: "Personalized Cashback Recommendations",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Recommend offers",
    legalBasis: "PERSONALIZED_RECOMMENDATIONS",
    dataCategories: ["preferences", "usage"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "13 months analytics-style",
    retentionJustification: "Legitimate interests + opt-out",
    crossBorderTransfers: true,
    transferSafeguards: "SCC",
    securityMeasures: ["minimization"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-006",
    activityName: "B2B Merchant Data Insights",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Aggregated insights for merchants",
    legalBasis: "B2B_DATA_AGGREGATION",
    dataCategories: ["aggregated behavioral"],
    dataSubjectCategories: ["registered users"],
    recipients: [{ name: "Merchants", role: "PROCESSOR", country: "Various" }],
    retentionPeriod: "Per contract",
    retentionJustification: "Separate explicit consent",
    crossBorderTransfers: true,
    transferSafeguards: "SCC",
    securityMeasures: ["aggregation", "k-anonymity goals"],
    dpiaRequired: true,
    dpiaReference: "legal/dpia/dpia-b2b-data-product.md",
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-007",
    activityName: "Customer Support (Intercom)",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Support tickets",
    legalBasis: "LEGITIMATE_INTERESTS / CONTRACT",
    dataCategories: ["contact", "ticket content"],
    dataSubjectCategories: ["registered users"],
    recipients: [{ name: "Intercom", role: "PROCESSOR", country: "US" }],
    retentionPeriod: "3 years",
    retentionJustification: "Support policy",
    crossBorderTransfers: true,
    transferSafeguards: "DPA + SCC",
    securityMeasures: ["access control"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-008",
    activityName: "Fraud Detection & Prevention",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Detect fraudulent claims",
    legalBasis: "FRAUD_DETECTION",
    dataCategories: ["transactions", "device signals"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "As needed for investigations",
    retentionJustification: "Legitimate interests + balancing test",
    crossBorderTransfers: false,
    transferSafeguards: null,
    securityMeasures: ["monitoring", "rate limits"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-009",
    activityName: "Product Analytics (Mixpanel/PostHog)",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Product improvement",
    legalBasis: "ANALYTICS_TRACKING",
    dataCategories: ["events", "pseudonymous ids"],
    dataSubjectCategories: ["registered users", "guests"],
    recipients: [
      { name: "Mixpanel", role: "PROCESSOR", country: "US" },
      { name: "PostHog", role: "PROCESSOR", country: "EU/US" },
    ],
    retentionPeriod: "13 months",
    retentionJustification: "Industry practice",
    crossBorderTransfers: true,
    transferSafeguards: "SCC + settings",
    securityMeasures: ["opt-out"],
    dpiaRequired: false,
    dpiaReference: "legal/dpia/dpia-behavioral-profiling.md",
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-010",
    activityName: "Infrastructure Monitoring (Datadog)",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Reliability and security monitoring",
    legalBasis: "LEGITIMATE_INTERESTS",
    dataCategories: ["logs", "metrics"],
    dataSubjectCategories: ["users (incidental)"],
    recipients: [{ name: "Datadog", role: "PROCESSOR", country: "US" }],
    retentionPeriod: "Per vendor",
    retentionJustification: "Security",
    crossBorderTransfers: true,
    transferSafeguards: "SCC",
    securityMeasures: ["scrubbing PII in logs"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-011",
    activityName: "Marketing Communications",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Promotions",
    legalBasis: "MARKETING_COMMUNICATIONS",
    dataCategories: ["contact", "preferences"],
    dataSubjectCategories: ["registered users"],
    recipients: [],
    retentionPeriod: "Until withdrawn",
    retentionJustification: "Consent",
    crossBorderTransfers: false,
    transferSafeguards: null,
    securityMeasures: ["unsubscribe"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
  {
    activityId: "PA-012",
    activityName: "Tax & Regulatory Reporting",
    controller: {
      name: "GoGoCash Co., Ltd.",
      address: "Thailand",
      dpoContact: "dpo@gogocash.co (example)",
    },
    purpose: "Compliance reporting",
    legalBasis: "TAX_REPORTING",
    dataCategories: ["financial"],
    dataSubjectCategories: ["registered users"],
    recipients: [{ name: "Authorities", role: "CONTROLLER", country: "TH" }],
    retentionPeriod: "Per law",
    retentionJustification: "Legal obligation",
    crossBorderTransfers: false,
    transferSafeguards: null,
    securityMeasures: ["restricted access"],
    dpiaRequired: false,
    dpiaReference: null,
    lastReviewed: new Date().toISOString().slice(0, 10),
    reviewedBy: "system-seed",
    status: "ACTIVE",
  },
];
