steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:latest"
      - "."
    id: "build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:$COMMIT_SHA"]
    waitFor: ["build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:latest"]
    waitFor: ["build"]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/gogocash-admin"
      - "gogocash-admin=us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:$COMMIT_SHA"
      - "-n"
      - "gogocash-staging"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=gogocash-staging-cluster"
    id: "deploy"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/gogocash/gogocash-admin-staging:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
