import { StyleSheet } from "react-native";

import { mobileShellLayout } from "@mobile/design/webDesignParity";
import { pickThemed, type ThemeColors } from "@mobile/theme/colorPalettes";
import { type ThemeSurfaces } from "@mobile/theme/themeSurfaces";
import { radii, shadows, spacing, typography } from "@mobile/theme/tokens";

export function createHomeScreenStyles(colors: ThemeColors, surfaces: ThemeSurfaces) {
  return StyleSheet.create({
  viewport: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
    position: "relative",
  },
  phoneFrame: {
    backgroundColor: colors.background,
    flex: 1,
    position: "relative",
    width: "100%",
  },
  desktopShellFrame: {
    backgroundColor: colors.background,
    flex: 1,
    position: "relative",
    width: "100%",
  },
  desktopContentCap: {
    alignSelf: "center",
    flexGrow: 0,
    gap: mobileShellLayout.desktopHomeStackGap,
    width: "100%",
  },
  desktopScrollContent: {
    flexGrow: 0,
    flexShrink: 0,
  },
  pageDesktopFullBleed: {
    paddingHorizontal: 0,
  },
  desktopFooterCap: {
    alignSelf: "center",
    flexGrow: 0,
    width: "100%",
  },
  desktopShell: {
    backgroundColor: colors.card,
    zIndex: 20,
    boxShadow: surfaces.desktopShellShadow,
  },
  desktopHeader: {
    alignItems: "center",
    backgroundColor: colors.card,
    height: mobileShellLayout.desktopHeaderHeight,
    justifyContent: "center",
    width: "100%",
  },
  desktopHeaderOverlayLayer: {
    position: "relative",
    zIndex: 120,
  },
  desktopHeaderContent: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 20,
    height: mobileShellLayout.desktopHeaderHeight,
    justifyContent: "space-between",
  },
  desktopLogoLink: {
    alignItems: "center",
    borderRadius: radii.md,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 44,
  },
  desktopLogoMark: {
    borderRadius: 16,
    height: 56,
    width: 56,
  },
  desktopLogoText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 28,
  },
  desktopHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
  },
  desktopQuestPill: {
    alignItems: "center",
    borderRadius: radii.chip,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 169,
  },
  desktopQuestImage: {
    height: 48,
    width: 169,
  },
  desktopSignIn: {
    alignItems: "center",
    borderRadius: radii.chip,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 160,
  },
  desktopLocaleButton: {
    alignItems: "center",
    backgroundColor: surfaces.localeButtonBackground,
    borderColor: surfaces.localeButtonBorder,
    borderRadius: radii.chip,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.12)",
  },
  desktopLocaleButtonOpen: {
    backgroundColor: surfaces.localeButtonOpenBackground,
    borderColor: surfaces.localeButtonOpenBorder,
  },
  desktopLocaleRoot: {
    position: "relative",
    zIndex: 90,
  },
  desktopLocalePopover: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: "0 18px 40px rgba(15, 23, 42, 0.16)",
    padding: 16,
    position: "absolute",
    right: 0,
    top: 52,
    width: 288,
    zIndex: 100,
  },
  desktopLocaleSectionTitle: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  desktopLocaleOptionStack: {
    gap: 2,
    marginTop: 8,
  },
  desktopLocaleOption: {
    alignItems: "center",
    borderRadius: 8,
    flexDirection: "row",
    gap: 10,
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  desktopLocaleOptionSelected: {
    backgroundColor: "#E8FAF5",
  },
  desktopLocaleOptionFlag: {
    fontSize: 18,
    lineHeight: 20,
  },
  desktopLocaleOptionLabel: {
    color: "#374151",
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  desktopLocaleOptionLabelSelected: {
    color: "#00CC99",
  },
  desktopLocaleDivider: {
    backgroundColor: colors.fieldMuted,
    height: 1,
    marginBottom: 16,
    marginTop: 16,
  },
  desktopLocaleRegionScroller: {
    height: 192,
    marginTop: 8,
    overflow: "hidden",
  },
  desktopLocaleRegionList: {
    gap: 2,
    paddingRight: 4,
  },
  desktopCategoryNav: {
    alignItems: "center",
    backgroundColor: colors.card,
    height: mobileShellLayout.desktopSubNavHeight,
    justifyContent: "center",
    width: "100%",
  },
  desktopCategoryNavInner: {
    alignItems: "center",
    alignSelf: "center",
    height: mobileShellLayout.desktopSubNavHeight,
    justifyContent: "center",
  },
  desktopCategoryNavScroller: {
    flexGrow: 0,
    height: 38,
  },
  desktopCategoryNavList: {
    alignItems: "flex-end",
    gap: 16,
    justifyContent: "center",
    minHeight: 38,
    transform: [{ translateX: -1.6 }],
  },
  desktopCategoryNavItem: {
    alignItems: "center",
    borderRadius: radii.sm,
    flexDirection: "row",
    gap: 8,
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    position: "relative",
  },
  desktopCategoryNavItemLead: {
    height: 40,
  },
  desktopCategoryNavIcon: {
    height: 16,
    width: 16,
  },
  desktopCategoryNavText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    lineHeight: 21,
  },
  desktopCategoryNavTextLead: {
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
  },
  desktopCategoryFire: {
    height: 16,
    width: 13,
  },
  desktopCategoryUnderline: {
    backgroundColor: "#00B14F",
    borderRadius: radii.chip,
    bottom: 0,
    height: 2,
    left: 16,
    position: "absolute",
    right: 16,
  },
  stickySearch: {
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
  },
  mobileTabletHomeHeader: {
    backgroundColor: "#009D78",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    boxSizing: "border-box",
    gap: 16,
    paddingBottom: 72,
    maxWidth: "100%",
    overflow: "hidden",
    paddingTop: 28,
    position: "relative",
    width: "100%",
    boxShadow: "0 18px 44px rgba(0, 89, 69, 0.18)",
  },
  mobileTabletHomeHeaderTablet: {
    paddingBottom: 54,
    paddingTop: 42,
  },
  mobileTabletHeaderTopRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
  },
  mobileTabletHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  mobileTabletHeaderGreeting: {
    color: "#FFFFFF",
    fontFamily: typography.family,
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 38,
  },
  mobileTabletHeaderSubcopy: {
    color: "rgba(255, 255, 255, 0.88)",
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 2,
  },
  mobileTabletHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  mobileTabletHeaderIconButton: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "#F7F8FA", "rgba(255, 255, 255, 0.16)"),
    borderRadius: 27,
    height: 54,
    justifyContent: "center",
    width: 54,
    boxShadow: "0 8px 18px rgba(48, 56, 70, 0.14)",
  },
  mobileHeaderIconButtonSmall: {
    borderRadius: 20,
    height: 40,
    width: 40,
  },
  mobileTabletHeaderSearchBox: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: 18,
    boxSizing: "border-box",
    flexDirection: "row",
    gap: 12,
    maxWidth: "100%",
    minHeight: 54,
    paddingHorizontal: 18,
    width: "100%",
    boxShadow: "0 9px 18px rgba(48, 56, 70, 0.12)",
  },
  mobileTabletHeaderSearchInput: {
    color: colors.ink,
    flex: 1,
    flexShrink: 1,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: "600",
    minWidth: 0,
    width: 0,
  },
  mobileTabletHeaderShortcutDock: {
    backgroundColor: colors.card,
    borderRadius: 22,
    display: "none",
    overflow: "hidden",
    paddingVertical: 4,
    boxShadow: "0 9px 20px rgba(48, 56, 70, 0.12)",
  },
  mobileTabletLegacySearchHidden: {
    display: "none",
  },
  mobileTabletPageScroll: {
    flex: 1,
    width: "100%",
  },
  mobileTabletPageScrollContent: {
    width: "100%",
  },
  mobileTabletContentScroll: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    boxSizing: "border-box",
    marginTop: -40,
    maxWidth: "100%",
    overflow: "visible",
    position: "relative",
    width: "100%",
  },
  mobileTabletSheetToggleButton: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: 12,
    boxShadow: "0 6px 18px rgba(15, 23, 42, 0.12)",
    height: 24,
    justifyContent: "center",
    left: "50%",
    marginLeft: -12,
    position: "absolute",
    top: -12,
    width: 24,
    zIndex: 4,
  },
  mobileTabletContentSheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingTop: 50,
  },
  searchPill: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 48,
    // Clip to the radius so the rounded corners don't rasterize "horns" under the focus layer.
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    boxShadow: shadows.cardCss,
  },
  searchPillActive: {
    borderColor: colors.primaryDark,
  },
  searchInput: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: typography.bodyWeight,
    height: 42,
    minWidth: 0,
    padding: 0,
  },
  searchText: {
    color: colors.muted,
    flex: 1,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
  },
  searchPopoverLayer: {
    ...StyleSheet.absoluteFill,
    zIndex: 30,
  },
  searchPopoverBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  searchPopoverPosition: {
    position: "absolute",
  },
  searchPopover: {
    backgroundColor: pickThemed(colors, "#FAFDFB", colors.card),
    borderColor: pickThemed(colors, "rgba(0, 170, 128, 0.1)", "rgba(0, 204, 153, 0.2)"),
    borderRadius: 20,
    borderWidth: 1,
    maxHeight: 640,
    overflow: "hidden",
    padding: 20,
    boxShadow: "0 16px 40px rgba(16, 53, 34, 0.12)",
  },
  searchPopoverScroll: {
    maxHeight: 600,
  },
  searchPopoverContent: {
    gap: spacing.md,
  },
  searchPopoverIntro: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "#F6FEF9", colors.primarySoft),
    borderColor: pickThemed(colors, "rgba(209, 250, 229, 0.9)", "rgba(0, 204, 153, 0.25)"),
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 96,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  searchPopoverIntroCompact: {
    minHeight: 82,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  searchTrendingIcon: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: radii.md,
    height: 64,
    justifyContent: "center",
    width: 64,
    boxShadow: shadows.cardCss,
  },
  searchTrendingIconCompact: {
    height: 52,
    width: 52,
  },
  searchIntroCopy: {
    flex: 1,
    minWidth: 0,
  },
  searchPopoverTitle: {
    color: pickThemed(colors, "#103522", colors.accent),
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 24,
  },
  searchPopoverTitleCompact: {
    fontSize: 14,
    lineHeight: 18,
  },
  searchPopoverSubtitle: {
    color: pickThemed(colors, "#5C7A9A", colors.muted),
    fontFamily: typography.family,
    fontSize: 18,
    fontWeight: typography.bodyWeight,
    lineHeight: 26,
    marginTop: 6,
  },
  searchPopoverSubtitleCompact: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  searchTypedContent: {
    gap: 12,
  },
  searchNoMatchCard: {
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.9)", colors.card),
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: pickThemed(colors, "#64748B", colors.muted),
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: typography.bodyWeight,
    lineHeight: 26,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchResultsHeading: {
    gap: 2,
  },
  searchResultsTitle: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 17,
    textTransform: "uppercase",
  },
  searchResultsSubtitle: {
    color: pickThemed(colors, "#64748B", colors.muted),
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    lineHeight: 19,
  },
  searchDivider: {
    backgroundColor: "rgba(0, 170, 128, 0.12)",
    height: 1,
  },
  searchResultList: {
    gap: 8,
  },
  searchResultListCompact: {
    gap: 8,
  },
  searchResultRow: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: pickThemed(colors, "#E8F0EC", colors.border),
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileShellLayout.searchPopoverResultRowGap,
    minHeight: 84,
    padding: spacing.sm,
    boxShadow: shadows.cardCss,
  },
  searchResultRowCompact: {
    borderColor: "transparent",
    borderRadius: radii.sm,
    minHeight: 56,
    padding: 8,
    boxShadow: "none",
  },
  searchResultLogo: {
    alignItems: "center",
    borderRadius: 14,
    height: 68,
    justifyContent: "center",
    overflow: "hidden",
    width: 68,
  },
  searchResultLogoCompact: {
    borderRadius: 8,
    height: 40,
    width: 40,
  },
  searchResultLogoText: {
    fontFamily: typography.family,
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 36,
  },
  searchResultLogoTextCompact: {
    fontSize: 20,
    lineHeight: 24,
  },
  searchResultCopy: {
    flex: 1,
    minWidth: 0,
  },
  searchResultName: {
    color: pickThemed(colors, "#1E3A5F", colors.ink),
    fontFamily: typography.family,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 23,
  },
  searchResultNameCompact: {
    fontSize: 14,
    lineHeight: 18,
  },
  searchResultCashbackRow: {
    alignItems: "baseline",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: 4,
  },
  searchResultCaption: {
    color: pickThemed(colors, "#7195B8", colors.muted),
    fontFamily: typography.family,
    fontSize: 15,
    fontWeight: typography.bodyWeight,
  },
  searchResultCaptionCompact: {
    fontSize: 11,
  },
  searchResultCashback: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "700",
  },
  searchResultCashbackCompact: {
    fontSize: 14,
  },
  searchResultAction: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.chip,
    height: 44,
    justifyContent: "center",
    minWidth: mobileShellLayout.searchPopoverActionMinWidth,
    paddingHorizontal: spacing.sm,
  },
  searchResultActionCompact: {
    height: 28,
    minWidth: 86,
    paddingHorizontal: 12,
  },
  searchResultActionText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: "700",
  },
  searchResultActionTextCompact: {
    fontSize: 11,
  },
  page: {
    gap: spacing.homeStackGap,
    paddingTop: mobileShellLayout.contentTopGap,
  },
  shortcutRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  shortcutPill: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    // Grow to fill each wrapped line (flexBasis stays auto, so content width
    // still drives where the row wraps): a balanced segmented nav on tablet,
    // an even 2x2 grid on phones — no dead space on the trailing edge.
    flexGrow: 1,
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: mobileShellLayout.shortcutPillHeight,
    paddingHorizontal: 12,
    boxShadow: shadows.cardCss,
  },
  shortcutText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: typography.caption,
    fontWeight: typography.labelWeight,
  },
  heroStack: {
    gap: spacing.sm,
  },
  heroStackDesktop: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: spacing.md,
  },
  heroBannerSection: {
    gap: spacing.sm,
    width: "100%",
  },
  heroBannerSectionDesktop: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: spacing.md,
  },
  mainHeroFrame: {
    borderRadius: radii.lg,
    overflow: "hidden",
    position: "relative",
    boxShadow: shadows.cardCss,
  },
  heroBannerLink: {
    backgroundColor: "#E8EAED",
  },
  heroScroll: {
    height: "100%",
    width: "100%",
  },
  heroScrollContent: {
    alignItems: "stretch",
  },
  heroSlide: {
    height: "100%",
    flexShrink: 0,
  },
  mainHeroFrameDesktop: {
    // Tuned (~2.07:1) so two 16:9 side banners + the 16px inner gap (which equals the
    // outer main->side gap) add up to exactly the main banner height at the desktop
    // content width: mainW = 2*sideW + (16/9)*gap.
    flex: 2.069,
  },
  sideHeroRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  sideHeroRowDesktop: {
    flex: 1,
    flexDirection: "column",
    // Inner gap between the two side banners == the outer main->side gap (both
    // spacing.md) so the hero spacing reads as one uniform gutter; the tuned main
    // flex above keeps the column aligned top-and-bottom with the main banner.
    gap: spacing.md,
  },
  sideHeroFrame: {
    borderRadius: radii.md,
    flex: 1,
    overflow: "hidden",
    position: "relative",
    boxShadow: shadows.cardCss,
  },
  sideHeroFrameMobile: {
    aspectRatio: mobileShellLayout.homeSideBannerAspectRatio,
  },
  sideHeroFrameDesktop: {
    // Lock each side frame to the 1920x1080 banner ratio so the full banner shows
    // (no cover-crop); size by aspect ratio rather than filling the column.
    aspectRatio: mobileShellLayout.homeSideBannerAspectRatio,
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
    minHeight: 0,
  },
  heroImage: {
    height: "100%",
    width: "100%",
  },
  heroDots: {
    alignItems: "center",
    bottom: spacing.md,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
  },
  heroDot: {
    // Over hero photos — keep a light dot in both themes for contrast on banner art.
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.55)", "rgba(255,255,255,0.55)"),
    borderRadius: radii.chip,
    height: 8,
    width: 8,
  },
  heroDotActive: {
    backgroundColor: colors.card,
  },
  desktopGoLinkBanner: {
    alignItems: "center",
    borderRadius: 32,
    flexDirection: "row",
    gap: 48,
    minHeight: 216,
    overflow: "hidden",
    paddingHorizontal: 32,
    paddingVertical: 24,
    position: "relative",
    width: "100%",
    boxShadow: "0 4px 10px rgba(4, 16, 34, 0.06), 0 25px 75px rgba(7, 33, 102, 0.12)",
  },
  mobileTabletGoLinkBanner: {
    alignItems: "stretch",
    alignSelf: "stretch",
    borderRadius: 24,
    boxSizing: "border-box",
    flexDirection: "column",
    gap: 14,
    maxWidth: "100%",
    minHeight: 0,
    paddingHorizontal: 20,
    paddingVertical: 20,
    width: "100%",
    boxShadow: "0 9px 22px rgba(48, 56, 70, 0.14)",
  },
  desktopGoLinkBackdrop: {
    backgroundColor: pickThemed(colors, "#EAF4FF", colors.card),
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  desktopGoLinkAccentGlow: {
    backgroundColor: "rgba(0, 204, 153, 0.22)",
    borderRadius: 360,
    bottom: -220,
    height: 420,
    position: "absolute",
    right: -40,
    width: 520,
  },
  desktopGoLinkInfoButton: {
    alignItems: "center",
    borderRadius: radii.chip,
    height: 24,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    top: 20,
    width: 24,
    zIndex: 3,
  },
  desktopGoLinkIllustrationWrap: {
    // Frosted disc holding the link glyph + GO badge (matches the approved preview).
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: pickThemed(colors, "rgba(255, 255, 255, 0.78)", "rgba(26, 31, 29, 0.88)"),
    borderColor: pickThemed(colors, "rgba(255, 255, 255, 0.9)", colors.borderStrong),
    borderRadius: 54,
    borderWidth: 1,
    flexShrink: 0,
    height: 108,
    justifyContent: "center",
    position: "relative",
    width: 108,
    zIndex: 1,
    boxShadow: pickThemed(
      colors,
      "0 18px 32px -14px rgba(6, 78, 59, 0.45)",
      "0 18px 32px -14px rgba(0, 0, 0, 0.55)",
    ),
  },
  mobileTabletGoLinkIllustrationWrap: {
    display: "none",
  },
  desktopGoLinkGoBadge: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: colors.border,
    borderRadius: 21,
    borderWidth: 3,
    bottom: -6,
    height: 42,
    justifyContent: "center",
    position: "absolute",
    right: -6,
    width: 42,
    boxShadow: "0 8px 18px -6px rgba(0, 204, 153, 0.7)",
  },
  desktopGoLinkGoBadgeText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  desktopGoLinkForm: {
    flex: 1,
    gap: 16,
    minWidth: 0,
    paddingRight: 28,
    zIndex: 1,
  },
  mobileTabletGoLinkForm: {
    paddingRight: 0,
    width: "100%",
  },
  desktopGoLinkEyebrow: {
    alignSelf: "flex-start",
    backgroundColor: pickThemed(colors, "rgba(255, 255, 255, 0.6)", "rgba(255, 255, 255, 0.08)"),
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 4,
  },
  desktopGoLinkEyebrowText: {
    color: pickThemed(colors, "#0A5C4A", colors.accent),
    fontFamily: typography.family,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  desktopGoLinkTitle: {
    color: pickThemed(colors, "#14252B", colors.ink),
    fontFamily: typography.family,
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  mobileTabletGoLinkTitle: {
    fontSize: 22,
    lineHeight: 28,
  },
  desktopGoLinkHeadlineRow: {
    alignItems: "flex-start",
    flexDirection: "column",
    gap: 12,
  },
  desktopGoLinkSteps: {
    alignItems: "center",
    flexDirection: "row",
    flexShrink: 1,
    flexWrap: "wrap",
    gap: 8,
    maxWidth: "100%",
  },
  desktopGoLinkStep: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255, 255, 255, 0.6)", colors.fieldMuted),
    borderColor: pickThemed(colors, "rgba(255, 255, 255, 0.75)", colors.borderStrong),
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  desktopGoLinkStepNum: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 9,
    height: 18,
    justifyContent: "center",
    width: 18,
  },
  desktopGoLinkStepNumText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
  },
  desktopGoLinkStepText: {
    color: pickThemed(colors, "#0A5C4A", colors.accent),
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "600",
  },
  desktopGoLinkStepArrow: {
    color: pickThemed(colors, "rgba(10, 92, 74, 0.45)", colors.accentSoft),
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: "700",
  },
  desktopGoLinkControls: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: 12,
  },
  mobileTabletGoLinkControls: {
    flexDirection: "column",
  },
  desktopGoLinkInputShell: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255, 255, 255, 0.95)", colors.field),
    borderColor: pickThemed(colors, "rgba(0, 170, 128, 0.35)", "rgba(0, 204, 153, 0.35)"),
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 10,
    height: 48,
    minWidth: 0,
    // Clip to the radius so the rounded corners don't rasterize "horns" under the focus layer.
    overflow: "hidden",
    paddingLeft: 16,
    paddingRight: 14,
    boxShadow: pickThemed(
      colors,
      "inset 0 1px 0 rgba(255, 255, 255, 0.9)",
      "inset 0 1px 0 rgba(255, 255, 255, 0.06)",
    ),
  },
  desktopGoLinkInputShellError: {
    borderColor: "#EF4444",
  },
  desktopGoLinkInput: {
    color: pickThemed(colors, "#2D3F3A", colors.ink),
    flex: 1,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: typography.bodyWeight,
    height: 46,
    minWidth: 0,
    padding: 0,
  },
  desktopGoLinkAction: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.chip,
    height: 48,
    justifyContent: "center",
    minWidth: 182,
    paddingHorizontal: 40,
    boxShadow: "0 8px 28px -6px rgba(0, 204, 153, 0.55)",
  },
  mobileTabletGoLinkAction: {
    minWidth: 0,
    width: "100%",
  },
  desktopGoLinkActionText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: "600",
  },
  desktopGoLinkError: {
    color: "#B91C1C",
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 17,
    marginTop: -14,
  },
  section: {
    gap: mobileShellLayout.homePromoSectionGap,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  titleRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minWidth: 0,
  },
  sectionTitle: {
    color: pickThemed(colors, "#103522", colors.accent),
    fontFamily: typography.family,
    fontSize: 18,
    fontWeight: typography.sectionTitleWeight,
    lineHeight: 24,
  },
  sectionTitleSmall: {
    color: pickThemed(colors, "#103522", colors.accent),
    flexShrink: 1,
    fontFamily: typography.family,
    fontSize: 18,
    fontWeight: typography.sectionTitleWeight,
    lineHeight: 24,
  },
  sectionEmoji: {
    fontSize: 18,
    lineHeight: 24,
  },
  topBrandEmoji: {
    fontSize: 18,
    lineHeight: 24,
  },
  sectionAction: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
  },
  topBrandPager: {
    gap: 14,
    overflow: "hidden",
    width: "100%",
  },
  topBrandScroll: {
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
  },
  topBrandPagerContent: {
    alignItems: "flex-start",
  },
  topBrandPage: {
    flexShrink: 0,
  },
  topBrandDots: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
  },
  topBrandDot: {
    backgroundColor: "#BFCFC8",
    borderRadius: radii.chip,
    height: 12,
    width: 12,
  },
  topBrandDotActive: {
    backgroundColor: colors.primary,
  },
  brandGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileShellLayout.topBrandGridGap,
  },
  compactBrandGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileShellLayout.compactBrandGridGap,
  },
  promoSectionBody: {
    gap: 14,
    overflow: "hidden",
    width: "100%",
  },
  promoScroll: {
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
  },
  promoPagerContent: {
    alignItems: "flex-start",
  },
  promoPage: {
    flexShrink: 0,
  },
  promoSectionDots: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
  },
  bottomNavWrap: {
    bottom: 0,
    left: 0,
    marginHorizontal: "auto",
    maxWidth: mobileShellLayout.bottomNavMaxWidth,
    paddingHorizontal: spacing.md,
    position: "absolute",
    right: 0,
  },
  bottomNav: {
    alignItems: "center",
    backgroundColor: surfaces.bottomNavBackground,
    borderColor: surfaces.bottomNavBorder,
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 86,
    paddingHorizontal: spacing.sm,
    boxShadow: shadows.bottomNavCss,
  },
  bottomNavItem: {
    alignItems: "center",
    borderRadius: radii.lg,
    flex: 1,
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 62,
  },
  bottomNavItemActive: {
    backgroundColor: colors.primarySoft,
  },
  bottomNavItemEmphasized: {
    marginTop: -22,
  },
  bottomNavIcon: {
    alignItems: "center",
    height: 28,
    justifyContent: "center",
    minWidth: 28,
  },
  bottomNavIconEmphasized: {
    backgroundColor: colors.primary,
    borderColor: colors.primarySoft,
    borderRadius: radii.chip,
    borderWidth: 8,
    height: 72,
    width: 72,
  },
  bottomNavLabel: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.caption,
    fontWeight: typography.navLabelWeight,
    maxWidth: 74,
  },
  bottomNavLabelEmphasized: {
    color: colors.accent,
  },
  bottomNavTextActive: {
    color: colors.primaryDark,
  },
});
}

export type HomeScreenStyles = ReturnType<typeof createHomeScreenStyles>;
