import { StyleSheet } from "react-native";

import { pickThemed, type ThemeColors } from "@mobile/theme/colorPalettes";
import { radii, shadows, spacing, typography } from "@mobile/theme/tokens";

export function createSearchScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    header: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      paddingBottom: spacing.sm,
      paddingHorizontal: spacing.md,
    },
    backButton: {
      alignItems: "center",
      borderRadius: radii.chip,
      height: 44,
      justifyContent: "center",
      width: 44,
    },
    searchFieldShell: {
      alignItems: "center",
      backgroundColor: colors.field,
      borderColor: colors.border,
      borderRadius: radii.chip,
      borderWidth: 1,
      flex: 1,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 48,
      paddingHorizontal: spacing.md,
    },
    searchFieldShellFocused: {
      borderColor: colors.primaryDark,
    },
    searchInput: {
      color: colors.ink,
      flex: 1,
      fontFamily: typography.family,
      fontSize: 16,
      fontWeight: typography.bodyWeight,
      minWidth: 0,
      padding: 0,
    },
    submitButton: {
      alignItems: "center",
      backgroundColor: colors.primary,
      borderRadius: 24,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    scrollContent: {
      alignSelf: "center",
      gap: spacing.md,
      paddingBottom: spacing.xl,
      paddingTop: spacing.md,
      width: "100%",
    },
    sectionBlock: {
      gap: spacing.sm,
    },
    sectionHeaderRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.xs,
    },
    sectionTitle: {
      color: colors.ink,
      fontFamily: typography.family,
      fontSize: 16,
      fontWeight: "700",
    },
    sectionSubtitle: {
      color: colors.muted,
      fontFamily: typography.family,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 18,
      marginBottom: spacing.sm,
    },
    clearHistoryButton: {
      alignItems: "center",
      borderRadius: radii.chip,
      flexDirection: "row",
      gap: spacing.xs,
      minHeight: 44,
      paddingHorizontal: spacing.xs,
    },
    clearHistoryLabel: {
      color: colors.muted,
      fontFamily: typography.family,
      fontSize: 13,
      fontWeight: "600",
    },
    recentScrollContent: {
      gap: spacing.sm,
      paddingRight: spacing.sm,
    },
    recentRow: {
      flexDirection: "row",
      gap: spacing.sm,
    },
    recentChip: {
      alignItems: "center",
      backgroundColor: pickThemed(colors, colors.fieldMuted, colors.field),
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.xs,
      maxWidth: 220,
      minHeight: 44,
      paddingLeft: 12,
      paddingRight: 8,
      paddingVertical: 0,
    },
    recentChipSelect: {
      flex: 1,
      justifyContent: "center",
      minHeight: 44,
      minWidth: 0,
    },
    recentChipText: {
      color: colors.ink,
      flex: 1,
      fontFamily: typography.family,
      fontSize: 14,
      fontWeight: "600",
      minWidth: 0,
    },
    recentChipRemove: {
      alignItems: "center",
      borderRadius: radii.chip,
      height: 32,
      justifyContent: "center",
      width: 32,
    },
    popularIntro: {
      alignItems: "center",
      backgroundColor: pickThemed(colors, "#F6FEF9", colors.primarySoft),
      borderColor: pickThemed(colors, "rgba(209, 250, 229, 0.9)", "rgba(0, 204, 153, 0.25)"),
      borderRadius: radii.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: 12,
      minHeight: 72,
      paddingHorizontal: spacing.md,
      paddingVertical: 12,
    },
    popularIntroCompact: {
      minHeight: 68,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    popularIntroIcon: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderRadius: radii.md,
      height: 48,
      justifyContent: "center",
      width: 48,
      boxShadow: shadows.cardCss,
    },
    popularIntroIconCompact: {
      height: 44,
      width: 44,
    },
    popularIntroCopy: {
      flex: 1,
      minWidth: 0,
    },
    popularIntroTitle: {
      color: pickThemed(colors, "#103522", colors.accent),
      fontFamily: typography.family,
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 22,
    },
    popularIntroTitleCompact: {
      fontSize: 15,
      lineHeight: 19,
    },
    popularIntroSubtitle: {
      color: pickThemed(colors, "#5C7A9A", colors.muted),
      fontFamily: typography.family,
      fontSize: 14,
      fontWeight: typography.bodyWeight,
      lineHeight: 20,
      marginTop: 2,
    },
    popularIntroSubtitleCompact: {
      fontSize: 12,
      lineHeight: 18,
      marginTop: 2,
    },
    trendingScrollContent: {
      gap: spacing.sm,
      paddingRight: spacing.sm,
    },
    trendingRow: {
      flexDirection: "row",
      gap: spacing.sm,
    },
    trendingChip: {
      alignItems: "center",
      backgroundColor: pickThemed(colors, colors.fieldMuted, colors.field),
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    trendingChipText: {
      color: colors.ink,
      fontFamily: typography.family,
      fontSize: 14,
      fontWeight: "600",
    },
    sectionDivider: {
      backgroundColor: "rgba(0, 170, 128, 0.12)",
      height: 1,
    },
    suggestionsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
    seeAllButton: {
      alignSelf: "flex-start",
      borderRadius: radii.chip,
      justifyContent: "center",
      marginTop: spacing.xs,
      minHeight: 44,
      paddingHorizontal: spacing.xs,
      paddingVertical: spacing.xs,
    },
    // Normal weight — it is a link, not a heading (design feedback 2026-07-10).
    seeAllLabel: {
      color: colors.primaryDark,
      fontFamily: typography.family,
      fontSize: 14,
      fontWeight: "400",
    },
    resultsSection: {
      gap: spacing.sm,
    },
    resultsHeading: {
      color: colors.ink,
      fontFamily: typography.family,
      fontSize: 16,
      fontWeight: "700",
    },
    resultsSubheading: {
      color: colors.muted,
      fontFamily: typography.family,
      fontSize: 13,
      fontWeight: "500",
    },
    noMatchCard: {
      backgroundColor: pickThemed(colors, colors.fieldMuted, colors.field),
      borderRadius: radii.md,
      color: colors.ink,
      fontFamily: typography.family,
      fontSize: 14,
      fontWeight: "500",
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
    },
    resultList: {
      gap: spacing.sm,
    },
  });
}
