import type { DataTransferAgreement } from "../types";

const nextYear = () => new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

export const DEFAULT_TRANSFER_AGREEMENTS: DataTransferAgreement[] = [
  {
    id: "ta-aws",
    provider: "AWS",
    serviceType: "infrastructure",
    dataCategories: ["hosting", "logs"],
    country: "US/SG",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: "2021",
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-atlas",
    provider: "MongoDB Atlas",
    serviceType: "database",
    dataCategories: ["application data"],
    country: "Various",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-gcp",
    provider: "Google Cloud / Firebase",
    serviceType: "auth / infra",
    dataCategories: ["auth tokens", "profile"],
    country: "US/EU",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-datadog",
    provider: "Datadog",
    serviceType: "monitoring",
    dataCategories: ["logs", "metrics"],
    country: "US",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-mixpanel",
    provider: "Mixpanel",
    serviceType: "analytics",
    dataCategories: ["pseudonymous events"],
    country: "US",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-posthog",
    provider: "PostHog",
    serviceType: "analytics",
    dataCategories: ["pseudonymous events"],
    country: "EU/US",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
  {
    id: "ta-intercom",
    provider: "Intercom",
    serviceType: "support",
    dataCategories: ["contact", "tickets"],
    country: "US",
    transferMechanism: "STANDARD_CONTRACTUAL_CLAUSES",
    sccSignedDate: null,
    sccVersion: null,
    dpaSignedDate: null,
    reviewDue: nextYear(),
    status: "ACTIVE",
  },
];
