import { StyleSheet } from "react-native";

import { mobileShellLayout } from "@mobile/design/webDesignParity";
import { pickThemed, type ThemeColors } from "@mobile/theme/colorPalettes";
import { radii, shadows, spacing, typography } from "@mobile/theme/tokens";

export function createDiscoveryScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
  viewport: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
  },
  phoneFrame: {
    backgroundColor: colors.background,
    flex: 1,
    maxWidth: mobileShellLayout.contentMaxWidth,
    position: "relative",
    width: "100%",
  },
  desktopShellFrame: {
    backgroundColor: colors.background,
    flex: 1,
    position: "relative",
    width: "100%",
  },
  desktopContentCap: {
    alignSelf: "center",
    // Without these the page title sits flush against the sticky header and each
    // section sits flush against the next — both gaps measured at 0px.
    gap: mobileShellLayout.desktopDirectorySectionGap,
    paddingTop: mobileShellLayout.desktopDirectoryTopGap,
    width: "100%",
  },
  desktopFooterCap: {
    alignSelf: "center",
    width: "100%",
  },
  pageDesktopFullBleed: {
    paddingHorizontal: 0,
  },
  stickySearch: {
    backgroundColor: colors.background,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  searchPill: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    boxShadow: shadows.cardCss,
  },
  searchText: {
    color: colors.muted,
    fontFamily: typography.family,
    flex: 1,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
  },
  page: {
    gap: spacing.homeStackGap,
    paddingBottom: mobileShellLayout.bottomNavClearance,
    paddingHorizontal: mobileShellLayout.contentHorizontalPadding,
  },
  desktopFooter: {
    marginTop: 0,
  },
  productDiscoveryPage: {
    gap: spacing.xl,
    paddingBottom: mobileShellLayout.bottomNavClearance,
    paddingHorizontal: mobileShellLayout.contentHorizontalPadding,
  },
  productDiscoveryHeader: {
    gap: spacing.sm,
    maxWidth: 672,
  },
  productDiscoveryTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
  },
  productDiscoveryTitleDesktop: {
    fontSize: 40,
    lineHeight: 48,
  },
  productDiscoverySubtitle: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
    lineHeight: 24,
  },
  productDiscoveryLayout: {
    width: "100%",
  },
  productDiscoveryLayoutDesktop: {
    alignItems: "flex-start",
    flexDirection: "row",
  },
  productDiscoveryMain: {
    gap: spacing.lg,
    minWidth: 0,
  },
  productDiscoveryMobileFilters: {
    gap: spacing.sm,
  },
  productDiscoveryMobileFilterRow: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  productDiscoverySidebar: {
    backgroundColor: colors.fieldMuted,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    flexShrink: 0,
    gap: spacing.md,
    padding: 24,
  },
  productDiscoverySidebarTitle: {
    color: colors.accent,
    fontFamily: typography.family,
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 28,
  },
  productDiscoverySidebarDivider: {
    backgroundColor: colors.border,
    height: 1,
    width: "100%",
  },
  productDiscoverySidebarList: {
    gap: spacing.sm,
  },
  productDiscoverySidebarButton: {
    alignItems: "center",
    borderRadius: 16,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 52,
    padding: 16,
    width: "100%",
  },
  productDiscoverySidebarButtonActive: {
    backgroundColor: colors.primaryDark,
  },
  productDiscoverySidebarIconCell: {
    alignItems: "center",
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  productDiscoverySidebarText: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
    lineHeight: 20,
  },
  productDiscoverySidebarTextActive: {
    color: colors.white,
    fontWeight: "500",
  },
  productDiscoveryFilterPanel: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    boxShadow: shadows.cardCss,
  },
  productDiscoverySearchBox: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 44,
    // Clip to the radius so the rounded corners don't rasterize "horns" under the focus layer.
    overflow: "hidden",
    paddingHorizontal: spacing.md,
  },
  productDiscoverySearchInput: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    minWidth: 0,
  },
  productDiscoverySortRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  productDiscoverySortLabel: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "500",
    marginRight: spacing.xs,
  },
  productDiscoveryPill: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  productDiscoveryPillActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  productDiscoveryCashbackPillActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryDark,
  },
  productDiscoveryPillText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 16,
  },
  productDiscoveryPillTextActive: {
    color: colors.white,
  },
  productDiscoveryCashbackPillTextActive: {
    color: colors.primaryDark,
  },
  productDiscoveryResultsCount: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: typography.bodyWeight,
    marginLeft: "auto",
  },
  productDiscoveryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  productDiscoveryCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: spacing.sm,
    overflow: "hidden",
    padding: spacing.sm,
    boxShadow: shadows.cardCss,
  },
  productDiscoveryImageFrame: {
    aspectRatio: 1,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  productDiscoveryImage: {
    height: "100%",
    width: "100%",
  },
  productDiscoveryDiscountBadge: {
    backgroundColor: colors.danger,
    borderRadius: radii.chip,
    left: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    position: "absolute",
    top: spacing.sm,
    boxShadow: shadows.cardCss,
  },
  productDiscoveryDiscountText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 13,
  },
  productDiscoveryFavoriteButton: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.95)", colors.card),
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    position: "absolute",
    right: spacing.sm,
    top: spacing.sm,
    width: 32,
    boxShadow: shadows.cardCss,
  },
  productDiscoveryCardBody: {
    flex: 1,
    gap: spacing.sm,
  },
  productDiscoveryCardTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    minHeight: 40,
  },
  productDiscoveryPriceRow: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  productDiscoveryPriceHint: {
    color: colors.muted,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 13,
    textTransform: "uppercase",
  },
  productDiscoveryPriceStack: {
    alignItems: "flex-end",
    flexShrink: 0,
    gap: 3,
  },
  productDiscoveryOriginalPrice: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 13,
    textDecorationLine: "line-through",
  },
  productDiscoveryPrice: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 22,
  },
  productDiscoveryShopNowButton: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radii.chip,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  productDiscoveryShopNowText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "700",
  },
  productDiscoveryTermsButton: {
    alignItems: "center",
    minHeight: 24,
    justifyContent: "center",
  },
  productDiscoveryTermsText: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 11,
    textAlign: "center",
    textDecorationLine: "underline",
  },
  productDiscoveryEmptyState: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    padding: spacing.lg,
  },
  productDiscoveryEmptyTitle: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    textAlign: "center",
  },
  productDiscoveryTermsLayer: {
    alignItems: "center",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    padding: spacing.lg,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 20,
  },
  productDiscoveryTermsBackdrop: {
    backgroundColor: "rgba(16,34,23,0.42)",
    bottom: 0,
    left: 0,
    opacity: 1,
    position: "absolute",
    right: 0,
    top: 0,
  },
  productDiscoveryTermsBackdropClosing: {
    opacity: 0,
  },
  productDiscoveryTermsCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.md,
    maxWidth: 520,
    padding: spacing.lg,
    transform: [{ translateY: 0 }],
    width: "100%",
    boxShadow: shadows.cardCss,
  },
  productDiscoveryTermsCardClosing: {
    opacity: 0,
    transform: [{ translateY: 16 }],
  },
  productDiscoveryTermsTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: typography.title,
    fontWeight: "800",
  },
  productDiscoveryTermsBody: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    lineHeight: 22,
  },
  productDiscoveryTermsCloseButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: colors.primaryDark,
    borderRadius: radii.chip,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  productDiscoveryTermsCloseText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "700",
  },
  shopDirectoryPage: {
    gap: 28,
    paddingBottom: mobileShellLayout.bottomNavClearance,
    paddingHorizontal: mobileShellLayout.contentHorizontalPadding,
  },
  shopDirectoryPromo: {
    gap: spacing.lg,
    width: "100%",
  },
  shopDirectoryPromoTitleFrame: {
    justifyContent: "center",
    minHeight: 56,
  },
  shopDirectoryPromoTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 22,
    fontWeight: "600",
    lineHeight: 28,
  },
  shopDirectoryPromoTitleDesktop: {
    fontSize: 40,
    lineHeight: 48,
  },
  shopDirectoryPromoSlide: {
    borderRadius: 24,
    boxShadow: shadows.cardCss,
    overflow: "hidden",
    position: "relative",
  },
  shopDirectoryPromoSlideLink: {
    flex: 1,
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  shopDirectoryPromoImage: {
    height: "100%",
    width: "100%",
  },
  shopDirectoryPromoVignette: {
    backgroundColor: "rgba(0,0,0,0.04)",
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    top: 0,
  },
  shopDirectoryPromoDots: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    minHeight: 12,
  },
  shopDirectoryHeader: {
    gap: spacing.md,
    maxWidth: 672,
  },
  shopDirectoryTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  shopDirectoryTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
  },
  shopDirectoryTitleDesktop: {
    fontSize: 40,
    lineHeight: 48,
  },
  shopDirectoryTitleIcon: {
    fontSize: 24,
    lineHeight: 32,
  },
  shopDirectorySubtitle: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
    lineHeight: 24,
  },
  shopDirectoryLayout: {
    width: "100%",
  },
  shopDirectoryLayoutDesktop: {
    alignItems: "flex-start",
    flexDirection: "row",
  },
  shopDirectoryCategoryAside: {
    flexShrink: 0,
    gap: spacing.md,
  },
  shopDirectoryCategoryAsideDesktop: {
    backgroundColor: colors.fieldMuted,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    padding: 24,
  },
  shopDirectoryCategoryTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 24,
  },
  shopDirectoryCategoryTitleDesktop: {
    color: colors.accent,
    fontSize: 24,
    lineHeight: 28,
  },
  shopDirectoryCategoryDivider: {
    backgroundColor: colors.border,
    height: 1,
    width: "100%",
  },
  shopDirectoryCategoryList: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  shopDirectoryCategoryListDesktop: {
    borderBottomWidth: 0,
    flexDirection: "column",
    paddingBottom: 0,
  },
  shopDirectoryCategoryButton: {
    alignItems: "center",
    borderRadius: 8,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 40,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  shopDirectoryCategoryButtonDesktop: {
    borderRadius: 16,
    gap: spacing.md,
    minHeight: 52,
    padding: 16,
    width: "100%",
  },
  shopDirectoryCategoryButtonActive: {
    backgroundColor: colors.primaryDark,
  },
  shopDirectoryCategoryIconCell: {
    alignItems: "center",
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  shopDirectoryCategoryText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    lineHeight: 18,
  },
  shopDirectoryCategoryTextActive: {
    color: colors.white,
    fontWeight: "500",
  },
  shopDirectoryMain: {
    gap: spacing.lg,
    minWidth: 0,
  },
  shopDirectoryFilterPanel: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    boxShadow: shadows.cardCss,
  },
  shopDirectorySearchBox: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 44,
    // Clip to the radius so the rounded corners don't rasterize "horns" under the focus layer.
    overflow: "hidden",
    paddingHorizontal: spacing.md,
  },
  shopDirectorySearchInput: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    minWidth: 0,
  },
  shopDirectoryPillRow: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  shopDirectoryPill: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  shopDirectoryPillActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  shopDirectoryPillText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 12,
    fontWeight: typography.bodyWeight,
    lineHeight: 16,
  },
  shopDirectoryPillTextActive: {
    color: colors.white,
  },
  // Unified sort-chip text (14 / 600) — mirrors the web app's text-sm font-semibold
  // sort pills and the category screen's sortPillText so every sort bar reads the same.
  directorySortPillText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: typography.bodyWeight,
    lineHeight: 20,
  },
  directorySortPillTextActive: {
    color: colors.white,
  },
  shopDirectorySortBlock: {
    gap: spacing.sm,
  },
  shopDirectorySortLabel: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "500",
  },
  shopDirectorySortRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  shopDirectoryResultsCount: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: typography.bodyWeight,
    marginLeft: "auto",
  },
  shopDirectoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  brandDirectoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  shopDirectoryStoreCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: spacing.sm,
    overflow: "hidden",
    padding: spacing.sm,
    boxShadow: shadows.cardCss,
  },
  shopDirectoryLogoTile: {
    alignItems: "center",
    aspectRatio: 1,
    borderRadius: 10,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  shopDirectoryLogoImage: {
    // expo-image gets no size from absolute-fill alone on Android new arch.
    height: "100%",
    width: "100%",
  },
  shopDirectoryLogoFallback: {
    color: "#FFFFFF",
    fontFamily: typography.family,
    fontSize: 22,
    fontWeight: typography.labelWeight,
    lineHeight: 28,
    textAlign: "center",
  },
  shopDirectoryCouponBadge: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.95)", colors.card),
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    left: 6,
    maxWidth: "82%",
    minHeight: 20,
    paddingHorizontal: 6,
    position: "absolute",
    top: 6,
    boxShadow: shadows.cardCss,
  },
  shopDirectoryCouponIcon: {
    fontSize: 11,
    lineHeight: 14,
  },
  shopDirectoryCouponText: {
    color: colors.ink,
    flexShrink: 1,
    fontFamily: typography.family,
    fontSize: 10,
    fontWeight: typography.bodyWeight,
    lineHeight: 12,
  },
  shopDirectoryFavoriteButton: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.92)", colors.card),
    borderRadius: radii.chip,
    height: 28,
    justifyContent: "center",
    position: "absolute",
    right: 8,
    top: 8,
    width: 28,
    boxShadow: shadows.cardCss,
  },
  shopDirectoryStoreMeta: {
    flex: 1,
    gap: spacing.xs,
  },
  shopDirectoryStoreName: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 19,
    minHeight: 38,
  },
  shopDirectoryCashbackRow: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "space-between",
    minHeight: 23,
  },
  shopDirectoryCashbackCaption: {
    color: colors.muted,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 11,
    fontWeight: typography.bodyWeight,
    lineHeight: 14,
  },
  shopDirectoryCashbackValue: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 22,
  },
  shopDirectoryStoreCategory: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 11,
    fontWeight: typography.bodyWeight,
    lineHeight: 14,
  },
  shopDirectoryEmptyState: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.lg,
  },
  shopDirectoryEmptyTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: typography.title,
    fontWeight: "700",
  },
  shopDirectoryEmptyBody: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    lineHeight: 22,
  },
  shopDirectoryPagination: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "center",
    marginTop: spacing.lg,
  },
  shopDirectoryPageButton: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    minWidth: 32,
    paddingHorizontal: spacing.sm,
  },
  shopDirectoryPageButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  shopDirectoryPageButtonDisabled: {
    opacity: 0.45,
  },
  shopDirectoryPageButtonText: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "600",
  },
  shopDirectoryPageButtonTextActive: {
    color: colors.white,
  },
  categoryDirectoryPage: {
    gap: spacing.lg,
    paddingBottom: mobileShellLayout.bottomNavClearance,
    paddingHorizontal: mobileShellLayout.contentHorizontalPadding,
  },
  categoryDirectoryHeader: {
    gap: spacing.md,
  },
  categoryDirectoryHeaderDesktop: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  categoryDirectoryTitleBlock: {
    gap: 22,
  },
  categoryDirectoryTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.lg,
    minWidth: 0,
  },
  categoryDirectoryTitle: {
    color: pickThemed(colors, "#103522", colors.accent),
    fontFamily: typography.family,
    fontSize: 26.4,
    fontWeight: "800",
    lineHeight: 30,
  },
  categoryDirectoryTitleDesktop: {
    fontSize: 40,
    lineHeight: 48,
  },
  categoryDirectoryTitleIcon: {
    fontSize: 32,
    lineHeight: 34,
    transform: [{ rotate: "-5deg" }],
  },
  categoryDirectoryCount: {
    color: pickThemed(colors, "#5B6B61", colors.muted),
    fontFamily: typography.family,
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 26,
  },
  categorySearchPanel: {
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.9)", colors.card),
    borderColor: colors.borderStrong,
    borderRadius: 26,
    borderWidth: 1,
    boxShadow: "0 18px 48px rgba(16, 34, 23, 0.08)",
    padding: 16,
    width: "100%",
  },
  categorySearchPanelDesktop: {
    maxWidth: 384,
  },
  categorySearchBox: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.72)", colors.field),
    borderColor: colors.borderStrong,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 48,
    // Clip to the radius so the rounded corners don't rasterize "horns" under the focus layer.
    overflow: "hidden",
    paddingHorizontal: spacing.md,
  },
  categorySearchInput: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: typography.bodyWeight,
    minWidth: 0,
  },
  categoryDirectoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  categoryDirectoryCard: {
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.9)", colors.card),
    borderColor: colors.borderStrong,
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: "0 16px 40px rgba(16, 34, 23, 0.08)",
    overflow: "hidden",
    padding: 12,
  },
  categoryDirectoryCardDesktop: {
    padding: 14,
  },
  categoryDirectoryImageFrame: {
    aspectRatio: 1.08,
    backgroundColor: pickThemed(colors, "#F8FBF5", colors.primarySoft),
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  categoryDirectoryImage: {
    height: "100%",
    width: "100%",
  },
  categoryDirectoryBadge: {
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.92)", colors.card),
    borderColor: colors.borderStrong,
    borderRadius: radii.chip,
    borderWidth: 1,
    left: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    position: "absolute",
    top: spacing.md,
  },
  categoryDirectoryBadgeText: {
    color: colors.accent,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 16,
  },
  categoryDirectoryCardBody: {
    flex: 1,
    gap: spacing.md,
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.md,
  },
  categoryDirectoryCardTitle: {
    color: pickThemed(colors, "#102217", colors.accent),
    fontFamily: typography.family,
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
    minHeight: 24,
  },
  categoryDirectoryCardTitleDesktop: {
    fontSize: 17,
    lineHeight: 24,
  },
  categoryDirectoryCardFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
    marginTop: "auto",
  },
  categoryDirectoryCardCta: {
    color: pickThemed(colors, "#5B6B61", colors.muted),
    flex: 1,
    fontFamily: typography.family,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  categoryDirectoryArrowCircle: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.borderStrong,
    borderRadius: radii.chip,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  categoryDirectoryArrowIcon: {
    transform: [{ rotate: "-45deg" }],
  },
  categoryDirectoryEmptyState: {
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.9)", colors.card),
    borderColor: colors.borderStrong,
    borderRadius: 24,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.lg,
  },
  categoryDirectoryEmptyTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: typography.title,
    fontWeight: "700",
  },
  categoryDirectoryEmptyBody: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    lineHeight: 22,
  },
  categoryDirectoryPagination: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.9)", colors.card),
    borderColor: colors.borderStrong,
    borderRadius: 28,
    borderWidth: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    boxShadow: "0 18px 48px rgba(16, 34, 23, 0.08)",
  },
  hero: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
    boxShadow: shadows.cardCss,
  },
  kicker: {
    color: colors.primaryDark,
    fontSize: typography.caption,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: {
    color: colors.ink,
    fontSize: typography.headline,
    fontWeight: "700",
  },
  body: {
    color: colors.muted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  chip: {
    backgroundColor: colors.primarySoft,
    borderRadius: radii.chip,
    color: colors.accent,
    fontSize: typography.caption,
    fontWeight: "800",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  primaryAction: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: colors.primary,
    borderRadius: radii.chip,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  primaryActionText: {
    color: colors.white,
    fontSize: typography.body,
    fontWeight: "700",
  },
  shortcutRow: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  shortcutPill: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  shortcutText: {
    color: colors.ink,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  section: {
    gap: spacing.sm,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: typography.title,
    fontWeight: "700",
  },
  sectionAction: {
    color: colors.primaryDark,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  cardRow: {
    gap: spacing.md,
    paddingRight: spacing.md,
  },
  offerCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.xs,
    minHeight: 148,
    padding: spacing.md,
    width: 168,
  },
  cardCategory: {
    color: colors.primaryDark,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  cardTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: typography.body,
    fontWeight: "800",
  },
  cashbackPill: {
    alignSelf: "flex-start",
    backgroundColor: colors.primarySoft,
    borderRadius: radii.chip,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  cashbackText: {
    color: colors.accent,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  cardAction: {
    color: colors.primaryDark,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  discoverSection: {
    gap: spacing.lg,
  },
  discoverHeader: {
    gap: spacing.xs,
  },
  discoverTitle: {
    color: pickThemed(colors, "#103522", colors.accent),
    fontFamily: typography.family,
    fontSize: typography.sectionTitle,
    fontWeight: typography.sectionTitleWeight,
    lineHeight: 34,
  },
  discoverSubtitle: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
    lineHeight: 22,
    marginTop: spacing.xs,
  },
  discoverLayout: {
    gap: spacing.lg,
    width: "100%",
  },
  discoverLayoutDesktop: {
    alignItems: "flex-start",
    flexDirection: "row",
  },
  discoverSidebar: {
    backgroundColor: colors.fieldMuted,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  discoverSidebarTitle: {
    color: colors.accent,
    fontFamily: typography.family,
    fontSize: typography.title,
    fontWeight: "700",
    lineHeight: 24,
  },
  discoverDivider: {
    backgroundColor: colors.border,
    height: 1,
    width: "100%",
  },
  discoverCategoryList: {
    gap: spacing.sm,
  },
  discoverCategoryButton: {
    alignItems: "center",
    borderRadius: radii.md,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 52,
    padding: spacing.md,
  },
  discoverCategoryButtonActive: {
    backgroundColor: colors.primaryDark,
  },
  discoverCategoryText: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.family,
    fontSize: typography.body,
    fontWeight: typography.bodyWeight,
  },
  discoverCategoryTextActive: {
    color: colors.white,
    fontWeight: "500",
  },
  productGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  productCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 12,
    overflow: "hidden",
    padding: 10,
    paddingBottom: 14,
    boxShadow: shadows.cardCss,
  },
  productImageFrame: {
    aspectRatio: 1,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  productImage: {
    height: "100%",
    width: "100%",
  },
  productFavoriteButton: {
    alignItems: "center",
    backgroundColor: pickThemed(colors, "rgba(255,255,255,0.95)", colors.card),
    borderColor: colors.border,
    borderRadius: radii.chip,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    position: "absolute",
    right: spacing.sm,
    top: spacing.sm,
    width: 32,
    boxShadow: shadows.cardCss,
  },
  productBody: {
    flex: 1,
    gap: spacing.sm,
    minHeight: 0,
  },
  productTitle: {
    color: colors.ink,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    minHeight: 40,
  },
  productTitleDesktop: {
    fontSize: 15,
    lineHeight: 21,
  },
  productPriceRow: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  productPriceLabel: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  productPrice: {
    color: colors.primaryDark,
    fontFamily: typography.family,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 22,
  },
  productPriceDesktop: {
    fontSize: 24,
    lineHeight: 26,
  },
  productShopButton: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radii.chip,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    marginTop: "auto",
    minHeight: 40,
  },
  productShopButtonText: {
    color: colors.white,
    fontFamily: typography.family,
    fontSize: 14,
    fontWeight: "600",
  },
  productTermsText: {
    color: colors.muted,
    fontFamily: typography.family,
    fontSize: 11,
    textAlign: "center",
    textDecorationLine: "underline",
  },
});
}
